-- Privacy-light first-party analytics. No names, phone numbers, emails or IP addresses.
begin;

create table if not exists public.shop_analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (
    event_name in ('page_view','search','product_view','add_to_cart','begin_checkout')
  ),
  path text,
  product_id text,
  search_query text,
  result_count integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists shop_analytics_events_name_time_idx
  on public.shop_analytics_events(event_name,created_at desc);

alter table public.shop_analytics_events enable row level security;
revoke all on public.shop_analytics_events from anon,authenticated;
grant all on public.shop_analytics_events to service_role;

commit;
